{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "1dfeeb67-9686-424e-98ce-5a917c792bbc",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "87787efb-52b0-4ff2-a863-3be1ba9bb361",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-20 01:35:30.016 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:35:30.018 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:35:31.561 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-04-20 01:35:31.562 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:35:31.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:35:31.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:35:31.567 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:35:31.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "st.set_page_config(page_title=\"Heart Health AI\", page_icon=\"❤️\")\n",
    "st.title(\"Heart Attack Risk Predictor\")\n",
    "st.write(\"Enter the patient's clinical details to analyze the risk.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "420c0dcb-939c-42db-8186-4433dcc43c17",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Loading the saved files\n",
    "model = pickle.load(open('heart_model.pkl', 'rb'))\n",
    "scaler = pickle.load(open('scaler.pkl', 'rb'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "988bacd3-0d17-4aa9-85a1-adb6a2fccaf6",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-20 01:41:49.964 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.966 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.972 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.974 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.980 Session state does not function when running a script without `streamlit run`\n",
      "2026-04-20 01:41:49.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.982 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.983 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.984 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.987 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.992 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.994 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.998 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.998 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:49.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.002 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.004 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.007 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.010 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.020 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.021 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.029 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.034 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.035 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.037 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.039 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.044 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.067 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:41:50.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "    st.subheader(\"Numerical Details\")\n",
    "    age = st.number_input(\"Age\", min_value=1, max_value=110, value=40)\n",
    "    resting_bp = st.number_input(\"Resting Blood Pressure (mm Hg)\", min_value=50, max_value=250, value=120)\n",
    "    cholesterol = st.number_input(\"Cholesterol (mg/dl)\", min_value=50, max_value=600, value=200)\n",
    "    max_hr = st.number_input(\"Max Heart Rate Achieved\", min_value=50, max_value=250, value=150)\n",
    "    oldpeak = st.number_input(\"Oldpeak (ST depression)\", min_value=0.0, max_value=10.0, value=0.0, step=0.1)\n",
    "\n",
    "with col2:\n",
    "    st.subheader(\"Categorical Details\")\n",
    "    sex = st.selectbox(\"Sex\", options=[\"M\", \"F\"])\n",
    "    \n",
    "    # ChestPainType: TA: Typical Angina, ATA: Atypical Angina, NAP: Non-Anginal Pain, ASY: Asymptomatic\n",
    "    chest_pain = st.selectbox(\"Chest Pain Type\", options=[\"ATA\", \"NAP\", \"ASY\", \"TA\"])\n",
    "    \n",
    "    # FastingBS: 1 if FastingBS > 120 mg/dl, 0 otherwise\n",
    "    fasting_bs = st.selectbox(\"Fasting Blood Sugar > 120 mg/dl\", options=[\"No\", \"Yes\"])\n",
    "    \n",
    "    # RestingECG: Normal, ST, LVH\n",
    "    resting_ecg = st.selectbox(\"Resting ECG Results\", options=[\"Normal\", \"ST\", \"LVH\"])\n",
    "    \n",
    "    # ExerciseAngina: Y: Yes, N: No\n",
    "    ex_angina = st.selectbox(\"Exercise Induced Angina\", options=[\"N\", \"Y\"])\n",
    "    \n",
    "    # ST_Slope: Up, Flat, Down\n",
    "    st_slope = st.selectbox(\"ST Slope Type\", options=[\"Up\", \"Flat\", \"Down\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "6b5a8ebf-23ed-41f9-8046-c70c28245314",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Dictionary based encoding (Model training ke logic ke hisaab se)\n",
    "# Sex_M: 1 for Male, 0 for Female\n",
    "sex_m = 1 if sex == \"M\" else 0\n",
    "\n",
    "# FastingBS\n",
    "fbs_val = 1 if fasting_bs == \"Yes\" else 0\n",
    "\n",
    "# ExerciseAngina_Y\n",
    "angina_y = 1 if ex_angina == \"Y\" else 0\n",
    "\n",
    "# ChestPainType (Assuming One-Hot Encoding order)\n",
    "cp_ata = 1 if chest_pain == \"ATA\" else 0\n",
    "cp_nap = 1 if chest_pain == \"NAP\" else 0\n",
    "cp_asy = 1 if chest_pain == \"ASY\" else 0\n",
    "\n",
    "# RestingECG\n",
    "ecg_st = 1 if resting_ecg == \"ST\" else 0\n",
    "ecg_lvh = 1 if resting_ecg == \"LVH\" else 0\n",
    "\n",
    "# ST_Slope\n",
    "slope_flat = 1 if st_slope == \"Flat\" else 0\n",
    "slope_up = 1 if st_slope == \"Up\" else 0\n",
    "\n",
    "# Sabko ek list mein dalo (ORDER MUST MATCH X_train columns!)\n",
    "# Maan lo tumhara training order ye tha:\n",
    "features_list = [\n",
    "    age, resting_bp, cholesterol, fbs_val, max_hr, oldpeak,\n",
    "    sex_m, cp_ata, cp_nap, cp_asy, ecg_st, ecg_lvh, angina_y, \n",
    "    slope_flat, slope_up\n",
    "]\n",
    "\n",
    "input_data = np.array([features_list])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "abaeb2c3-221e-449c-a124-62d7eeff9022",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-20 01:50:19.889 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:50:19.891 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:50:19.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:50:19.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:50:19.896 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 01:50:19.897 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "if st.button(\"Analyze Risk\"):\n",
    "    # 1. Scaling\n",
    "    input_scaled = scaler.transform(input_data)\n",
    "    \n",
    "    # 2. Probability nikaalo\n",
    "    prob = model.predict_proba(input_scaled)[:, 1]\n",
    "    \n",
    "    # 3. Custom Threshold (0.45)\n",
    "    if prob >= 0.45:\n",
    "        st.error(f\"⚠️ High Risk! Probability: {prob[0]:.2f}\")\n",
    "        st.write(\"The patient shows symptoms consistent with heart disease.\")\n",
    "    else:\n",
    "        st.success(f\"✅ Low Risk. Probability: {prob[0]:.2f}\")\n",
    "        st.write(\"Everything looks normal, but always consult a doctor for certainty.\")\n",
    "\n",
    "\n",
    "    # Plotting Feature Importance\n",
    "    st.subheader(\"🔍 Model Decision Insights\")\n",
    "    st.write(\"This chart shows which factors influenced the AI's decision the most.\")\n",
    "\n",
    "    # Model se importance nikaalo\n",
    "    importances = model.feature_importances_\n",
    "    feature_names = [\n",
    "        'Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',\n",
    "        'Sex_M', 'ChestPain_ATA', 'ChestPain_NAP', 'ChestPain_ASY', \n",
    "        'RestingECG_ST', 'RestingECG_LVH', 'ExerciseAngina_Y', \n",
    "        'ST_Slope_Flat', 'ST_Slope_Up'\n",
    "    ]\n",
    "\n",
    "    # DataFrame banao plot karne ke liye\n",
    "    feat_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})\n",
    "    feat_df = feat_df.sort_values(by='Importance', ascending=False).head(10)\n",
    "\n",
    "    # Plotting logic\n",
    "    fig, ax = plt.subplots()\n",
    "    sns.barplot(x='Importance', y='Feature', data=feat_df, ax=ax, palette='viridis')\n",
    "    plt.title(\"Top Contributing Factors\")\n",
    "\n",
    "    # Streamlit mein plot dikhane ka tarika\n",
    "    st.pyplot(fig)\n",
    "\n",
    "    # Prediction logic ke andar\n",
    "    st.write(f\"Confidence Level: {prob[0]*100:.1f}%\")\n",
    "    st.progress(float(prob[0])) # Blue bar jo probability dikhayegi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d4e2c367-881c-44b8-9c21-c89ffe15cc74",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
